server:
  port: 8083

spring:
  application:
    name: tg-bot-service

bot:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_BOT_CHAT_ID}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: error