server:
  port: 8082

spring:
  application:
    name: api-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

twitch:
  client-id: ${TWITCH_CLIENT_ID}
  client-secret: ${TWITCH_CLIENT_SECRET}
  redirect-uri: ${TWITCH_REDIRECT_URI}
  user-id: ${TWITCH_USER_ID}