server:
  port: 8082

spring:
  application:
    name: api-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

twitch:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  grant-type: authorization_code
  redirect-uri: ${REDIRECT_URI}