server:
  port: 8082

spring:
  application:
    name: api-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_API_DB_HOST:localhost}:${POSTGRES_API_DB_PORT:5433}/${POSTGRES_API_DB_NAME:homethings_api_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"

twitch:
  client-id: ${TWITCH_CLIENT_ID}
  client-secret: ${TWITCH_CLIENT_SECRET}
  redirect-uri: ${TWITCH_REDIRECT_URI}
  user-id: ${TWITCH_USER_ID}

youtube:
  api-key: ${YOUTUBE_API_KEY}
  channel-id: ${YOUTUBE_CHANNEL_ID}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: error


