version: '3.7'

services:
  homethings-db:
    image: postgres:14.1-alpine
    container_name: homethings-db
    restart: always
    environment:
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - homethings-data:/var/lib/postgresql/data

  frontend:
    image: verpul/homethings:frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - '80:8080'

  eureka-service:
    image: verpul/homethings:eureka-service
    container_name: eureka-service
    restart: unless-stopped

  gateway-service:
    image: verpul/homethings:gateway-service
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "9000:9000"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak
    restart: unless-stopped
    command:
      - start --db postgres --http-enabled true --import-realm
    environment:
      KC_DB_URL: jdbc:postgresql://homethings-db:5432/homethings_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
    volumes:
      - type: bind
        source: ./keycloak/HomeThingsRealm.json
        target: /opt/keycloak/data/import/HomeThingsRealm.json
        read_only: true
    ports:
      - "8900:8080"
    depends_on:
       - homethings-db

  local-service:
    image: verpul/homethings:local-service
    container_name: local-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: homethings-db
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - homethings-db

  api-service:
    image: verpul/homethings:api-service
    container_name: api-service
    restart: unless-stopped
    depends_on:
      - eureka-service
      - local-service

volumes:
  homethings-data:
