version: '3.7'

services:
  frontend:
    build: ./frontend-service
    container_name: frontend
    restart: unless-stopped
    ports:
      - '80:8080'

  homethings-db:
    image: postgres:14.1-alpine
    container_name: homethings-db
    restart: always
    environment:
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - homethings-data:/var/lib/postgresql/data

  local-service:
    build:
      context: .
      dockerfile: ./local-service/Dockerfile
    container_name: local-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: homethings-db
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - homethings-db

  api-service:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
    container_name: api-service
    restart: unless-stopped
    ports:
      - "8082:8082"

volumes:
  homethings-data: