version: '3.7'

services:
  homethings-db:
    image: postgres:14.1-alpine
    container_name: homethings-db
    restart: always
    environment:
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "5432"
    volumes:
      - homethings-data:/var/lib/postgresql/data

  frontend:
    image: verpul/homethings:frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}
    ports:
      - '80:8080'

  eureka-service:
    image: verpul/homethings:eureka-service
    container_name: eureka-service
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE}

  gateway-service:
    image: verpul/homethings:gateway-service
    container_name: gateway-service
    restart: unless-stopped
    environment:
      SERVER_HOST: ${SERVER_HOST}
      TZ: ${TIMEZONE}
    ports:
      - "9000:9000"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: keycloak
    restart: unless-stopped
    command:
      - start --db postgres --http-enabled true --hostname-strict false --http-port 8900
    environment:
      KC_DB_URL: jdbc:postgresql://homethings-db:5432/homethings_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "8900:8900"
    depends_on:
       - homethings-db

  local-service:
    image: verpul/homethings:local-service
    container_name: local-service
    restart: unless-stopped
    environment:
      POSTGRES_HOST: homethings-db
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    ports:
      - "8081"
    depends_on:
      - homethings-db

  api-service:
    image: verpul/homethings:api-service
    container_name: api-service
    restart: unless-stopped
    environment:
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      TWITCH_REDIRECT_URI: ${TWITCH_REDIRECT_URI}
      TWITCH_USER_ID: ${TWITCH_USER_ID}
      TZ: ${TIMEZONE}
    ports:
      - "8082"

  tg-bot-service:
    image: verpul/homethings:tg-bot-service
    container_name: tg-bot-service
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_CHAT_ID: ${TELEGRAM_BOT_CHAT_ID}
      TZ: ${TIMEZONE}
    ports:
      - "8083"
    depends_on:
      - local-service
      - eureka-service

volumes:
  homethings-data:
