version: '3.7'

services:
  homethings-db:
    image: postgres:14.1-alpine
    container_name: homethings-db
    restart: always
    environment:
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - homethings-data:/var/lib/postgresql/data

  frontend:
    image: verpul/homethings:frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - '80:8080'

  local-service:
    image: verpul/homethings:backend-local
    container_name: backend-local
    restart: unless-stopped
    environment:
      POSTGRES_HOST: homethings-db
      POSTGRES_DB: homethings_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      - homethings-db

  api-service:
    image: verpul/homethings:backend-api
    container_name: backend-api
    restart: unless-stopped
    ports:
      - "8082:8082"

volumes:
  homethings-data:
