drop table  if exists weight_records;
drop table if exists reminder_category cascade;
drop table if exists reminders cascade ;

create table if not exists reminder_category
(
    id    int8 generated by default as identity,
    title varchar(100),
    primary key (id)
);

create table reminders
(
    id            int8 generated by default as identity,
    comment       varchar(500),
    completed     boolean      not null,
    expire_date   date,
    nesting_depth int4,
    period        varchar(255),
    periodic      boolean      not null,
    periodicity   int4,
    remind_date   date,
    remind_time   time,
    title         varchar(200) not null,
    category_id   int8,
    parent_id     int8,
    primary key (id)
);

create table weight_records
(
    id                  int8 generated by default as identity,
    weight_record_date  date       not null,
    weight_record_value varchar(4) not null,
    primary key (id)
);

alter table if exists weight_records
    add constraint weight_record_date_unique unique (weight_record_date);

alter table if exists reminder_category
    add constraint reminder_category_title_unique unique (title);

alter table if exists reminders
    add constraint reminder_category_foreign_key
        foreign key (category_id)
            references reminder_category;

alter table if exists reminders
    add constraint reminder_parent_foreign_key
        foreign key (parent_id)
            references reminders

