spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET, POST, PUT, DELETE, PATCH"
      routes:
        - id: local-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/reminder/**, /api/weight/**
        - id: api-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/weather, /api/rates/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: