server:
  port: 9000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: local-service
          uri: http://local-service:8081
          predicates:
            - Path=/api/reminder/**, /api/weight/**
        - id: api-service
          uri: http://api-service:8082
          predicates:
            - Path=/api/weather, /api/rates/**