spring:
  cloud:
    gateway:
      routes:
        - id: local-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/reminder/**, /api/weight/**, /api/currency/**
        - id: api-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/weather, /api/rates/**, /api/twitch/**, /api/vk/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8900/realms/HomeThingsRealm

logging:
  level:
    root: info
