server:
  port: 8081

spring:
  application:
    name: local-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_LOCAL_DB:localhost}:5432/${POSTGRES_LOCAL_DB:homethings_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: "classpath:db/changelog/changelog-master.xml"
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: error

