spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
      data-locations: classpath*:db/devdata/data.sql

  liquibase:
    enabled: false

logging:
  level:
    root: info