spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/devdata/schema.sql
      data-locations: classpath*:db/devdata/data.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info