spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath*:db/devdata/schema.sql
      data-locations: classpath*:db/devdata/data.sql

  liquibase:
    enabled: false

logging:
  level:
    root: info