server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  logging:
    minimum-event-level: error

