name: HomeThings CI

on:
  workflow_dispatch:

jobs:
  copy-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy docker-compose.yaml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "docker-compose.yml"
          target: ${{secrets.PROJECT_FOLDER}}
          overwrite: true
           
