name: HomeThings CI without check

on:
  workflow_dispatch:

jobs:
  copy-compose:
    name: Push docker-compose to remote server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Copy docker-compose.yaml via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "docker-compose.yml"
          target: ${{secrets.PROJECT_FOLDER}}
          overwrite: true
      - name: Copy keycloak setting via SSH
          uses: appleboy/scp-action@master
          with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USER}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            source: "keycloak"
            target: ${{secrets.PROJECT_FOLDER}}
            overwrite: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build-and-push-images, copy-compose ]
    steps:
      - name: Run command on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ${{secrets.PROJECT_FOLDER}}
            echo POSTGRES_USER=${{secrets.POSTGRES_USER}} > .env
            echo POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}} >> .env
            echo KC_ADMIN=${{secrets.KC_ADMIN}} >> .env
            echo KC_ADMIN_PASSWORD=${{secrets.KC_ADMIN_PASSWORD}} >> .env
            
            docker-compose --file docker-compose.yml down;
            docker-compose --file docker-compose.yml --env-file .env up -d
            docker system prune --all --force;
            rm .env
         
