name: HomeThings CI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{env.SSH_HOST}}
          user: ${{env.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
           cd ${{env.PROJECT_FOLDER}};
           echo I'm here;
           
